### ISSUE TITLE
Add new block 

### ISSUE THREAD

**Issue by bryanlikescode** [Developer-DUCS/BlockchainSim#52]

**Comment by bryanlikescode** [comment]
priority:medium status:in-progress type:feature

**Comment by lpareja99** [comment]
@lpareja99 
- Problem with wallets: change wallArr to wallets. AKA passes it through the methods and does not call it from import to be able to use it later to create a block.
- Make sure the whole app is still working after that.

**Comment by bvalencia002** [comment]
DONE

**Comment by bvalencia002** [comment]
DONE
